# -*- coding: utf-8 -*-
"""02. 파이썬 - 클래스(상속).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zIqVHTk0eDUfs7edNbW480_xJhbYvIKe

# 상속 (inheritance)

기반 형식에 정의한 멤버는 파생 형식에 상속한다.


    ex) 음악가 형식에 '이름', '연주하다' 를 캡슐화하면

    음악가에서 파생한 형식인 피아니스트는 자동으로 '이름', '연주하다' 멤버를 갖게 된다.

  설계 시점에서는 프로그램에 사용할 인스턴스들 중에 공통점을 찾아 여러 형식의 공통점을 기반 형식으로 정의하는 작업을 진행한다.
  
  이를 일반화(Generalization)라 부른다.

  (파생 형식) is a (기반 형식) 관계일 때 사용한다.
"""

class Man:
  def __init__(self, name):
    self.__name = name
  def introduce(self):
    print("my name is ", self.__name)

m1 = Man("홍길동")
m1.introduce()

class Student(Man):
  def __init__(self, name, num):
    super().__init__(name)
    self.__num = num
  def view(self):
    print("-------self 메서드-------")
    self.introduce()
    print("my number is ", self.__num)
    print("-------------------------")

s1 = Student("강감찬", 2)
s1.view()
s1.introduce()

if isinstance(s1, Man):
  print("사람입니다.")
else:
  print("사람이 아닙니다.")