# -*- coding: utf-8 -*-
"""03. 파이썬 - 책걸이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFYTMXfS4TeQqCvXnyrJ8h6kXgZ6ITOn
"""

url = "http://api.odcloud.kr/api/15098910/v1/uddi:a5ff8a87-db3e-4317-bc95-9283aa1dd4a2"
page_param = "page=1"
size_param = "perPage=10"
rt_param = "returnType=JSON" # or XML
auth_param = "serviceKey=%2FmPX9JMP12bAzgFCCCViMk%2BP2z6LqfctAnP8FpO%2BR7tTu%2FHGo%2FXLEzBakc5%2Fo8ADu2iGl0JmJNujCMpbgG%2Fr1w%3D%3D"
query_str = url+"?"+page_param+"&"+size_param+"&"+rt_param+"&"+auth_param
query_str

import urllib.request
import json

req = urllib.request.Request(query_str)
# req.add_header('Authorization', 'Infuser %2FmPX9JMP12bAzgFCCCViMk%2BP2z6LqfctAnP8FpO%2BR7tTu%2FHGo%2FXLEzBakc5%2Fo8ADu2iGl0JmJNujCMpbgG%2Fr1w%3D%3D')
res = urllib.request.urlopen(req)
datas = res.read().decode('utf-8')
print(datas)

#from datetime import datetime

#class CovidData:
#  def __init__(self, dt, dcnt, ccnt):
#    self.dt = dt
#    self.dcnt = dcnt
#    self.ccnt = ccnt

#  staticmethod # 객체와 관련된 메소드이나 객체 안에 들어가는 메소드는 아님, self가 들어가지 않음, 형식메서드, 정적 메서드
#  def make_covid_data(src):
#    dt = datetime.strptime(src['구분'], '%Y-%m-%d')
#    dcnt = src['사망자']
#    ccnt = src['확진자']
#    return CovidData(dt, dcnt, ccnt)
import sys
sys.path.append('/content/drive/MyDrive/seSac/python/module/')

from coviddata import CovidData

# datetime 활용
# dt = datetime.strptime('2020-01-31','%Y-%m-%d')
# print(dt)
# print(type(dt))

# def make_covid_date(src):
#  dt = datetime.strptime(src['구분'], '%Y-%m-%d')
#  dcnt = src['사망자']
#  ccnt = src['확진자']
#  return CovidData(dt, dcnt, ccnt)

import json
jres = json.loads(datas)
cdata = jres['data']

cds = []

for raw_cd in cdata:
  cds.append(CovidData.make_covid_data(raw_cd))

for cd in cds:
  print(f"일자:{cd.dt} 사망자:{cd.dcnt} 확진자:{cd.ccnt}")