# -*- coding: utf-8 -*-
"""04. 데이터분석 시각화-Preview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hbq1Mlk37a4pXaqkQn7X93Gx8IbOhIyM

# numpy 소개
"""

l1 = [1, 2, 'a', False] # 원소에 공통점이 없어서 자료 가공이 불편함

import numpy as np

na = np.array([1, 2, 3, 4, 5])
np.sum(na), np.min(na), np.max(na), np.var(na), np.std(na)

l2 = [[1, 2, 3], [2, 3], [4, 5, 6, 7]] # 같은 타입으로 묶여있으나 자료의 크기가 달라 가공 어려움

nb = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("차원 : ", nb.ndim)
print("구조 : ", nb.shape)
print(nb) # 1차원

nb = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
print("차원 : ", nb.ndim)
print("구조 : ", nb.shape)
print(nb) # 2차원, 1x12 행렬, 1개의 원소 + 원소 안애 12개

nb = nb.reshape(3, 4) # 3x4 배열로 재구조화
print("차원 : ", nb.ndim)
print("구조 : ", nb.shape)
print(nb) # 2차원, 3x4 행렬, 3개의 원소 + 원소 안에 4개

l1 = [[1, 2], [3, 4]]
l2 = [[3, 4], [2, 7]]

# 리스트를 합쳐줌
l3 = l1 + l2
print(l3)

# matrix 연산
na1 = np.array(l1)
na2 = np.array(l2)
na3 = na1 + na2
print(na3)

"""# pandas 소개

## matplotlib
"""

import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 최소한 y값은 전달해야 함, x값 전달 안 할 경우 0부터 순차적으로 부여
plt.show()

plt.plot([1, 2, 3, 4, 5, 6, 7, 8, 9], "y^")
plt.show()

plt.plot([2, 3, 4, 5, 6, 7, 8, 9, 15], [1, 2, 3, 4, 5, 6, 7, 8, 9], "ro") # x 목록, y 목록, 그래프 옵션
plt.show()

data = {'a': np.arange(50),
        'c': np.random.randint(0, 50, 50),
        'd': np.random.randn(50)}
data['b'] = data['a'] + 10 * np.random.randn(50)
data['d'] = np.abs(data['d']) * 100

plt.scatter('a', 'b', c='c', s='d', data=data)
plt.xlabel('entry a')
plt.ylabel('entry b')
plt.show()

plt.pie([123,45,20])
plt.show()

ratio = [34, 32, 16, 18]
labels = ['Apple', 'Banana', 'Melon', 'Grapes']
colors = ['#ff9999', '#ffc000', '#8fd9b6', '#d395d0']
wedgeprops = {'width': 0.7, 'edgecolor':'w', 'linewidth':5}

plt.pie(ratio, labels=labels, autopct='%.1f%%', startangle=260, counterclock=False, colors=colors, wedgeprops=wedgeprops)
plt.show()