# -*- coding: utf-8 -*-
"""04.파이썬 - 함수(파일처리).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18YPedgsOPV4Z2K6c_4WpKZegDoM-hzvA

# 파일 처리

파일 열기
"""

fp = '/content/drive/MyDrive/seSac/python/demo.txt'
fs = open(fp, 'r')
data = fs.read()
fs.close()
print(data)

"""파일 생성(수정)
- open(fp, 'w') : write 모드, 파일 존재할 경우 모든 내용 지우고 열어줌
- open(fp, 'a') : 파일의 끝으로 이동, 파일 끝에 새로운 내용 추가
"""

fp = '/content/drive/MyDrive/seSac/python/demo2.txt'
fs = open(fp, 'w') # write 모드, 파일 존재할 경우 모든 내용 지우고 열어줌
fs.write("Plz")
fs.close()

fp = '/content/drive/MyDrive/seSac/python/demo2.txt'
fs = open(fp, 'r')
data = fs.read()
fs.close()
print(data)

"""# 맛보기"""

import pandas as pd

mr = pd.read_csv('/content/drive/MyDrive/seSac/python/mushrooms.csv')
mr

mcs = mr['class']
mcs