# -*- coding: utf-8 -*-
"""05.파이썬 - 함수 실습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vJWixETO7M4uNj9oGO2E-wt8qaYtVXG
"""

folder = '/content/drive/MyDrive/seSac/python/'

# 매트릭스
members = [
           ["홍길동",90,85,88],
           ["을지문덕",80,88,90],
           ["강감찬",90,95,100]
          ]

fname = folder+"mscores.csv"
fname

""""mscores.csv" 파일 생성 + 데이터 입력하기"""

# 기본 라이브러리 사용

# with블록 끝나는 순간 열었던 파일을 닫아줌 - 파일 닫기를 깜빡하는 현상 방지
# with open(fname, 'w') as fs:
#  print("um")

fs = open(fname, 'w')
# 각 줄의 요소를 하나하나 넣어줌 (구분자 = ',', 행 구분='\n')
for member in members:
  fs.write(f"{member[0]}, {member[1]}, {member[2]}, {member[3]}\n")
fs.close()

# csv 라이브러리 사용(1)

import csv
fname2 = folder+"mscores2.csv"
with open(fname2, 'w', newline='') as csvfile:
    sw = csv.writer(csvfile, delimiter=',')
    # 한 행씩 넣어줌
    for member in members:
      sw.writerow(member)

# csv 라이브러리 사용(2)

import csv
fname2 = folder+"mscores2.csv"
fs = open(fname2, 'w', newline='')
sw = csv.writer(fs, delimiter=',')
# 한 행씩 넣어줌
for member in members:
  sw.writerow(member)
fs.close()

"""읽기 모드로 열기"""

fs = open(fname, 'r')
data = fs.read()
fs.close()
print(data)

fs = open(fname, 'r')
while True:
  record = fs.readline()
  if record == "":
    print("음냐뤼:", record)
    print("EOR : ", type(record))
    break
  print(record)
fs.close()

fs = open(fname, 'r')
members2 = []
while True:
  record = fs.readline()
  if record == "":
    break
  record = record.replace('\n', "")
  sdata = record.split(',')
  rs = []
  rs.append(sdata[0])
  for i in range(1, 4):
    rs.append(int(sdata[i]))
  members2.append(rs)
fs.close()
print(members2)

import csv
members3 = []
fs = open(fname, 'r', newline='')
reader = csv.reader(fs)
for row in reader:
  rs = []
  rs.append(row[0])
  for i in range(1,4):
    rs.append(int(row[i]))
  members3.append(rs)
fs.close()
print(members3)

import pandas as pd
members = pd.read_csv(fname, header=None)
members.info()
members.describe()