# -*- coding: utf-8 -*-
"""07.파이썬-문자열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2fzoP5LmjKO3AysdkK9pCjzWUuS3WLl
"""

s1 = "aBcDeFgHiJkLmNoPqRsTuVwXyZ"
len(s1) # 문자열 길이

s1.upper() #대문자로 바꾼 문자열을 알려줌, 원본(s1)은 그대로

s1

s1.lower() # 소문자로 바꾼 문자열을 알려줌, 원본(s1)은 그대로

s1

s1[16] # 인덱서로 접근, 인덱서 안 - 인덱스(0부터 시작)

s2 = "          abcde            "
s2.strip() # 양옆 공백 제거

"123 fdsaf".isalnum(), "asdfjsdafdsa324fdafef".isalnum(), "sadf#fdsfjhuasef".isalnum(), "123dfsaf".isalnum()

s3 = "I am a boy. You are a girl. HelLovenus~"
s3.find("a "), s3.rfind("a ")

"Hello" in s3

res = s3.split(' ')
res