# -*- coding: utf-8 -*-
"""04.파이썬-자료형-기타.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AZDhCY08IeCBHKjw1mvCv1UxWRMvglxV

#입력값 casting 오류 - 추후 오류처리 학습에서 해결
"""

korea = int(input("국어 점수:"))
print("국어 :", korea)