# -*- coding: utf-8 -*-
"""02. 통계분석시각화 - Pandas 입출력.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eC9hU2-L5ZBGqz8Q0ye97KQZfi4KSchv

#Pandas 입출력

df = pd.read_csv(경로)
"""

import pandas as pd
df = pd.read_csv('/content/sample_data/sea_rain1.csv')
df

df2 = pd.read_csv('/content/sample_data/sea_rain1.txt', sep='-')
print(df2)

df.to_csv('demo.csv')

df3 = pd.read_csv('/content/sample_data/demo2.csv', header=None)
print(df3)

df3.columns = ["연도", "동해", "남해", "서해", "전체"]
df3

"""#실습예"""

import pandas as pd
path = '/content/sample_data/train_titanic.csv'
data = pd.read_csv(path)
data.info()

data['Survived'].value_counts() # 분포 세기

data['Pclass'].value_counts()

# 전처리

names_values = ['None', 'Mr', 'Mrs', 'Miss', 'Master', 'Dr']
ndata = data['Name']

# 각 이름마다 체크
for ne in ndata:
  # ','를 기준으로 분리
  f, s = ne.split(',')

  # ',' 뒤에 있는 문자열을 '.'으로 분리
  ses = s.split('.')

  # '.'의 앞부분에 공백 제거
  s0 = ses[0].replace(' ', '')

  # names_values에 있는지 체크
  check = False
  for i, ne2 in enumerate(names_values):
    # 호칭 있을 경우 출력
    if ne2 == s0:
      print(i)
      check = True
      break

  # 호칭 없을 경우
  if check == False:
    print(0)

# enumerate
datas = ["a", "b", "c"]
for i, d in enumerate(datas):
  print(i, d)

sdata = data['Sex']
for j, sd in enumerate(sdata):
  if sd == 'female':
    sdata[j] = 0
  else:
    sdata[j] = 1

data