# -*- coding: utf-8 -*-
"""colab_init.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17cw24JTVtJ9TDlKm_mqzHB_QtvvlGI6v
"""

# Commented out IPython magic to ensure Python compatibility.
# %run my_init.py

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline