# -*- coding: utf-8 -*-
"""02. 파이썬 - 모듈(math, random, sys, os, datetime, time).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDSoa_5JP1B-r31Tq1waskfFJN3zJr0B

#math 모듈
"""

import math

print(f"{math.sin(math.pi):.5f}")
print(f"{math.cos(math.pi):.5f}")
print(f"{math.tan(math.pi):.5f}")
print(f"{math.ceil(math.pi):.5f}") # 올림
print(f"{math.floor(math.pi):.5f}") # 내림
print(f"{round(math.pi):.5f}") # 반올림

from math import sin,cos,tan

print(f"{sin(math.pi):.5f}")
print(f"{cos(math.pi):.5f}")
print(f"{tan(math.pi):.5f}")
print(f"{math.ceil(math.pi):.5f}") # 올림
print(f"{math.floor(math.pi):.5f}") # 내림
print(f"{round(math.pi):.5f}") # 반올림

import math as m

print(f"{sin(math.pi):.5f}")
print(f"{cos(math.pi):.5f}")
print(f"{tan(math.pi):.5f}")
print(f"{m.ceil(math.pi):.5f}") # 올림
print(f"{m.floor(math.pi):.5f}") # 내림
print(f"{round(math.pi):.5f}") # 반올림

"""# random 모듈

런타임 초기화했을 때 같은 값이 나올 수도 있음

시드가 자동생성되는지 재확인 필요

- random.random() : 0~1 사이의 랜덤한 값을 반환
"""

import random

for i in range(100):
  print(f"{random.random():8.5f}", end=' ')
  if i%10 == 9:
    print()
print()

"""* random.randrange(n:정수) : 0 ~ n-1 까지의 정수 중에 랜덤한 값을 반환

* random.randrange(s:정수, e:정수) : s ~ e-1 까지의 정수 중에 랜덤한 값을 반환
"""

for i in range(100):
  print(f"{random.randrange(10):8.5f}", end=' ')
  if i%10 == 9:
    print()
print("=========================================================================================")
for i in range(100):
  print(f"{random.randrange(10, 20):8.5f}", end=' ')
  if i%10 == 9:
    print()

"""* random.uniform(s, e) : s~e 사이의 랜덤한 실수를 반환"""

for i in range(100):
  print(f"{random.uniform(10, 20):8.5f}", end=' ')
  if i%10 == 9:
    print()

"""* random.shuffle(목록) : 목록의 요소를 랜덤하게 섞어줌"""

ls = [1,2,3,4,5,6,7,8,9,10]
random.shuffle(ls)
ls

"""* random.choice(목록) : 목록의 요소 중 무작위로 하나 뽑아줌"""

for i in range(100):
  print(f"{random.choice(ls):8d}", end=' ')
  if i%10 == 9:
    print()

"""* random.sample(목록, k=개수) : 목록 요소 중 무작위로 k개를 선택(샘플링)"""

ls = list(range(1, 46))
print(ls)
random.sample(ls, k=6)

"""# sys 모듈

시스템과 관련된 정보를 가지고 있는 모듈

* ping -t python.org 라는 명령어를 cmd에서 실행했을 때,

  ping : 프로그램명

  -t, python.org : argv(프로그램 진입 전 전달해주는 값)
"""

import sys

sys.argv
len(sys.argv)

"""# os 모듈"""

import os
os.name

"""# datetime 모듈"""

import datetime
n = datetime.datetime.now()
n.day

"""# time 모듈"""

import time
print("a", end=' ')
time.sleep(1)
print("b", end=' ')
time.sleep(1)
print("c", end=' ')
time.sleep(1)
print("d", end=' ')
time.sleep(1)
print("...")

s = time.time()
for lc in range(10000):
  for _ in range(10000):
    i+=1
  if(lc % 1000 == 0):
    print(".", end="")
e = time.time()
print(e-s)

"""# urllib 모듈"""

from urllib import request

html = request.urlopen('http://docs.python.org')
print(html.read())