# -*- coding: utf-8 -*-
"""dummy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnJW25-Bdp3uw95cXDhN4y1MQ2O5fryY
"""

def print_n(s, n=1):
  for i in range(n):
    print(f"{i+1} s")
print_n("hello", 3)

def print_list(ls):
  for i, elem in enumerate(ls):
    print(f"{i+1} : {elem}")

if __name__ == "__main__": # 현재 파일의 main이 진입점일 때 수행하시오.
  print_n("hello", 3)
  print_list([1,2,3])