# -*- coding: utf-8 -*-
"""d08_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ibC6JB9iUBemk8DwWDLo2x8JXavm0_6O
"""

# Commented out IPython magic to ensure Python compatibility.
# %run my_init.py

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

wine = pd.read_csv("https://bit.ly/wine_csv_data")
wine.head(3)

data = wine.drop('class', axis=1).to_numpy()
data.shape

target = wine['class'].to_numpy()
target.shape

train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

train_input.shape, train_target.shape

test_input.shape, test_target.shape

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

from sklearn.model_selection import cross_validate

scores = cross_validate(dt, train_input, train_target, cv=3, return_train_score=True)
scores

np.mean(scores['test_score']) # validation score

np.mean(scores['train_score'])

from sklearn.model_selection import KFold, StratifiedKFold

kfold = KFold(3, shuffle=True, random_state=42)
skfold = StratifiedKFold(3, shuffle=True, random_state=42)

scores = cross_validate(dt, train_input, train_target, cv=skfold, return_train_score=True)
scores

np.arange(0.0001, 0.0006, 0.0001)

for i, v in enumerate(np.arange(0.0003, 0.0008, 0.0001)):
  dt = DecisionTreeClassifier(min_impurity_decrease=v, random_state=42)
  scores = cross_validate(dt, train_input, train_target, cv=skfold, return_train_score=True)
  print(f"[{i+1}]")
  print(f"train score: {np.mean(scores['train_score'])}")
  print(f"test score: {np.mean(scores['test_score'])}", end="\n\n")

from sklearn.model_selection import GridSearchCV

dt = DecisionTreeClassifier(random_state=42)
params = {
    "max_depth": range(3, 6),
    "min_samples_split": [2, 5, 8],
    "min_impurity_decrease": np.arange(0.0001, 0.0006, 0.0001)
}

3 * 3 * 5 * 5

gs = GridSearchCV(dt, params, cv=5, n_jobs=-1)
gs.fit(train_input, train_target)

gs.best_estimator_

gs.best_params_

gs.best_score_

gs.cv_results_.keys()

gs.cv_results_['mean_test_score']

np.max(gs.cv_results_['mean_test_score'])

best_model = gs.best_estimator_
best_model.get_params()

best_model.score(train_input, train_target)

best_model.score(test_input, test_target)