/* TRANSACTION 실습 */

/* 고립성 : 트랜잭션을 수행중인 현재 세션에서는 조회가 가능하고,
            다른 세션에서는 변경이 진행중인 데이터를 조회할 수 없음
            변경 이전 상태의 데이터 조회 가능
*/
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES(90, '사업부', '경기도');
UPDATE EMP SET DEPTNO = 90 WHERE DEPTNO = 30;
DELETE FROM DEPT WHERE DEPTNO = 30;
SELECT * FROM DEPT;
SELECT * FROM EMP WHERE DEPTNO = 30;
ROLLBACK;
SELECT * FROM DEPT;
SELECT * FROM EMP;


/* 
    COMMIT을 통해 트랜잭션에서 발생한 모든 변경사항을 저장한 후 트랜잭션이 종료되었기때문에
    ROLLBACK 대상이 없음
*/
INSERT INTO EMP(EMPNO, ENAME, JOB, SAL) VALUES(1111, 'ORACLE', 'DBA', 3500);
UPDATE EMP SET SAL = SAL * 1.3 WHERE EMPNO=1111;
COMMIT;
ROLLBACK;
SELECT * FROM EMP;


/*
    DML 명령어에서 에러 발생 시 해당 명령어에 의해 변경된 데이터만 자동으로 ROLLBACK
    (Statement level ROLLBACK)
    원자성에 의해 모두 취소되어야하지만 DELETE와 UPDATE가 적용됨 → EXCEPTION 기능 사용해야 함
*/
ROLLBACK; -- 임의 트랜잭션 종료
DELETE FROM EMP WHERE EMPNO = 1111;
UPDATE EMP SET SAL = 1234 WHERE EMPNO = 7902;
UPDATE EMP SET SAL = 123456789 WHERE EMPNO = 7788;
COMMIT;
SELECT EMPNO, SAL FROM EMP WHERE EMPNO IN (1111,7788,7902);

BEGIN
    DELETE FROM EMP WHERE DEPTNO = 20;
    UPDATE EMP SET SAL = 123456789 WHERE EMPNO = 7499;
    UPDATE EMP SET SAL = 1234 WHERE EMPNO = 7698;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;
/ -- 슬래시로 꼭 닫아줘야함
SELECT DEPTNO, EMPNO, SAL FROM EMP WHERE DEPTNO = 20 OR EMPNO IN (7499,7698);


/* TRANSACTION과 DDL */

INSERT INTO EMP(EMPNO, ENAME, DEPTNO) VALUES(9999,'OCPOK', 20);
ALTER TABLE EMP ADD(SEX CHAR(1) DEFAULT 'M'); -- DDL, 성별 탭 추가
ROLLBACK; -- ALTER 취소 안됨, DDL은 입력하면 COMMIT 자동 실행
DESC EMP;
ALTER TABLE EMP DROP COLUMN SEX;
ROLLBACK;
DESC EMP;