# -*- coding: utf-8 -*-
"""02. 파이썬 - 반복문(리스트 편).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLb1QL25NlOL7PBEsS5Ujgk3yWC3WbOE

# for문
"""

for i in range(10):
  print(i, end=' ')

ls = [3, 4, 8, 9]
for i in ls:
  print(i, end=' ')

input = "홍길동"

ls=['홍길동', '강감찬', '고길동', '음냐뤼']
name = input("검색할 회원 : ")
if name in ls:
  print("존재합니다.")
else:
  print("없는 회원입니다.")

"""# 간단한 연습 문제

10명의 회원 이름을 입력받아 출력하시오.
"""

member_names = []
for i in range(10):
  name = input(f"{i+1}번째 이름 : ")
  member_names.append(name)
print(member_names)

"""국어, 영어, 수학 점수를 입력받아 평균을 구하여 출력하시오.

단, 점수는 리스트에 보관
"""

# 1.
scores = []
sum = 0
for i in range(3):
  score = int(input("점수 입력: "))
  sum += score
  scores.append(score)
print(sum/3)

# 2.
subjects=("국어", "영어", "수학")
scores = [] # 점수 기억할 컬렉션 생성
for i in range(len(subjects)):  # 반복(3과목)
  score = int(input(f"{subjects[i]} 점수 입력")) # 점수 입력
  scores.append(score)  # 컬렉션에 보관
print((scores[0]+scores[1]+scores[2])/3)  #평균 출력