# -*- coding: utf-8 -*-
"""05 파이썬 - 반복문(관련 함수).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YA8Ai6AWEcqrzwQqtsYhkLggjmKgqIdc

# 리스트 관련 함수
"""

ls = [10, 98, 11, 23, 45, 77, 6]
print("최솟값 : ", min(ls))
print("최댓값 : ", max(ls))
print("합계 : ", sum(ls))

ls.sort()
print(ls)
ls.reverse()
print(ls)

rls = reversed(ls)
for elem in rls:
  print(elem, end=' ')
print()
print(ls)

ls = [3, 4, 5, 10, 23, 45, 9]
els = enumerate(ls)
print(els)

print(list(els))

# 대부분 사용하는 폼
ls = [3, 4, 5, 10, 23, 45, 9]
for index, elem in enumerate(ls):
  print(f"{index}:{elem}")

"""# 딕셔너리"""

ex_dict = {}
ex_dict["홍길동"] = 78
ex_dict["고길동"] = 88
ex_dict["김길동"] = 76
ex_dict["강길동"] = 88

print(ex_dict.items())

# 키 값 소용은 대부분 해당 방식
for key, value in ex_dict.items():
  print(f"key:{key} value:{value}")

sdict = sorted(ex_dict)
print(sdict)



"""# 고급진 리스트 컴프리핸션

3의 배수 구하기
"""

ls = []
#for i in range(0, 100, 3):
for i in range(1, 100):
  if i % 3 == 0:
    ls.append(i)
print(ls)

ls = [i for i in range(1, 100) if i % 3== 0]
print(ls)

"""1~100까지 정수로 구하기"""

ls = []
for i in range(1,100):
  ls.append(i)
print(ls)

ls = [i for i in range(1, 100)]
print(ls)