# -*- coding: utf-8 -*-
"""06. 파이썬 - 실습문제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JfuQb93tY9wOofe7pU5L9L2_YxA4lTFx

# 소개 ~ 반복문 실습
1. 사용자로부터 삼각형의 밑변과 높이를 입력받아 넓이를 출력하시오.
밑변과 높이는 실수를 입력할 수 있으며 넓이는 소수점 이하 2째 자리까지 출력하시오.
"""

length = float(input("삼각형 밑변 : "))
height = float(input("삼각형 높이 : "))
area = length*height/2
print("삼각형의 넓이 : {0:.2f}".format(area))

# Ver.강사님
bottom = float(input("밑변:"))
height = float(input("높이:"))
print(f"넓이:{(bottom*height/2):.2f}")

"""2. 두 개의 정수를 입력받아 작은 수가 큰 수의 약수인지 아닌지를 출력하시오."""

num1 = int(input("첫번째 숫자 입력 : "))
num2 = int(input("두번째 숫자 입력 : "))
if num1 > num2:
  num1, num2 = num2, num1
if num2 % num1 == 0:
  print(f"{num1}는 {num2}의 약수입니다.")
else:
  print(f"{num1}는 {num2}의 약수가 아닙니다.")

# Ver.강사님

num1 = int(input("첫번째 정수:"))
num2 = int(input("두번째 정수:"))

if num1 > num2:
  num1, num2 = num2, num1

if num2 % num1 == 0:
  print("약수")
else:
  print("노약수")

"""3. 두 개의 정수를 입력받아 두 개의 정수 사이의 정수의 합계를 구하여 출력하시오."""

num1 = int(input("첫번째 숫자 입력 : "))
num2 = int(input("두번째 숫자 입력 : "))
if num1 > num2:
  num1, num2 = num2, num1
sum = 0
for i in  range(num1, num2+1):
  sum+=i
print(f"두 숫자 사이의 합 : {sum}")

# Ver.강사님
num1 = int(input("첫번째 숫자 입력 : "))
num2 = int(input("두번째 숫자 입력 : "))
s = 0
if num1 > num2:
  num1, num2 = num2, num1
for i in range(num1, num2+1):
  s += i
print(f"{num1} ~ {num2} 합계:{s}")

"""4. n개의 정수를 입력받아 평균과 표준 편차를 구하시오."""

n = int(input("입력할 정수의 개수 : "))
avg = 0

number_list = []
for i in range(n):
  num = int(input(f"{i+1}번째 정수 입력 : "))
  avg += num
  number_list.append(num)
avg/=n

sum = 0
for i in range(n):
  sum += (number_list[i]-avg)**2
std_dev = (sum/n)**(1/2)
print("평균 : {0:.2f}, 표준편차 : {1:.2f}".format(avg, std_dev))

import math
import numpy

n = int(input("입력할 정수의 개수 : "))

number_list = []
for i in range(n):
  number_list.append(int(input(f"{i+1}번째 정수 입력 : ")))

num_mean = numpy.mean(number_list)
num_var = numpy.var(number_list)
std = numpy.std(number_list)

print("평균 : {0:.2f}, 표준편차 : {1:.2f}".format(num_mean, std))

# Ver. 강사님 (1)

n = int(input("입력할 원소의 개수 : "))
nums=[]
for num in range(n):
  num = int(input(f"{num+1}번째 정수 : "))
  nums.append(num)
avg = sum(nums)/n
print("평균:{avg}")
ss = 0
for elem in nums:
  ss += (avg - elem)**2
var = ss/n # 분산
stddev = var**(1/2) # 표준편차

# Ver. 강사님 (2)
import math

n = int(input("입력할 원소의 개수 : "))
nums=[]
for num in range(n):
  num = int(input(f"{num+1}번째 정수 : "))
  nums.append(num)
avg = sum(nums)/n
print(f"평균:{avg}")
ss = 0
for elem in nums:
  ss += (avg - elem)**2
var = ss/n # 분산
stddev = math.sqrt(var) # 표준편차
print(f"표준 편차: {stddev:.2f}")

"""5. n명의 국어, 영어, 수학 점수를 입력받아 출력하시오."""

subjects=("국어", "영어", "수학")
len = int(input("입력할 인원 수 : "))
students_dic = {}
for i in range(len):
  scores = []
  # 이름 입력
  name = input(f"{i+1}번째 학생 이름 : ")
  # 점수 입력
  for j in range(3):
    scores.append(int(input(f"{subjects[j]} 점수 입력 : ")))
  students_dic[name] = scores

print(students_dic)

# Ver.강사님

subjects = ("국어", "영어", "수학")
n = int(input("입력할 원소의 개수 : "))
m_dict = dict()
for i in range(n):
  name = input(f"{i+1}번째 학생 이름 : ")
  scores=[]
  for subject in subjects:
    score = int(input(f"{subject} 점수 : "))
    scores.append(score)
  m_dict[name] = scores
print(m_dict)

"""6. n명의 국어, 영어, 수학 점수를 입력받아 과목별 합계, 평균, 표준 편차를 출력하시오."""

subjects=("국어", "영어", "수학")
len = int(input("입력할 인원 수 : "))
students_list = []
avg_list = [0, 0, 0]

for i in range(len):
  scores = []
  print(f"{i+1}번째 학생")
  # 점수 입력
  for j in range(3):
    score = int(input(f"{subjects[j]} 점수 입력 : "))
    scores.append(score)
    avg_list[j] += score
  students_list.append(scores)

# 각 과목 평균
for i in range(3):
  avg_list[i] /= len

# 각 과목 표준편차
std_dev = [0, 0, 0]
for i in range(len):
  for j in range(3):
    std_dev[j] += ((students_list[i][j] - avg_list[j])**2)/len

for i in range(3):
  std_dev[i] **= (1/2)

print("------------------------")
# 출력
for i in range(3):
  print(f"{subjects[i]}")
  print("평균 : {0:.2f}, 표준편차 : {1:.2f}".format(avg_list[i], std_dev[i]))

import math
import numpy

kor = []
eng = []
math = []
len = int(input("입력할 인원 수 : "))

for i in range(len):
  print(f"{i+1}번째 학생")
  # 점수 입력
  kor.append(int(input("국어 점수 입력 : ")))
  eng.append(int(input("영어 점수 입력 : ")))
  math.append(int(input("수학 점수 입력 : ")))

print('---------------------')
# 출력
print("국어 평균 : {0:.2f}, 표준편차 : {1:.2f}".format(numpy.mean(kor), numpy.std(kor)))
print("영어 평균 : {0:.2f}, 표준편차 : {1:.2f}".format(numpy.mean(eng), numpy.std(eng)))
print("수학 평균 : {0:.2f}, 표준편차 : {1:.2f}".format(numpy.mean(math), numpy.std(math)))

# Ver.강사님
import math

subjects = ("국어", "영어", "수학")
n = int(input("입력할 원소의 개수 : "))

scores = []
scores.append([]) # 국어
scores.append([]) # 영어
scores.append([]) # 수학

for i in range(n):
  for si, subject in enumerate(subjects):
    score = int(input(f"{subject} 점수 : "))
    scores[si].append(score)

for si, subject in enumerate(subjects):
  avg = sum(scores[si])/len(scores[si])
  print(f"{subjects[si]} 합계 : {sum(scores[si])}")
  print(f"{subjects[si]} 평균 : {avg:.2f}")
  ss = 0
  for score in scores[si]:
    ss += (avg-score)**2
  var = ss/n # 분산
  stddev = math.sqrt(var)
  print(f"{subjects[si]} 표준편차: {stddev:.2f}")